version: 2.1

jobs:
  check-config-pack:
    resource_class: small
    docker:
      # https://github.com/CircleCI-Public/circleci-cli
      - image: circleci/circleci-cli:alpine
    steps:
      - checkout
      - run:
          name: CircleCIの設定ファイルを再生成して、コミットされているファイルと差分がないかチェック
          command: |
            # circleci config pack .circleci/src > .circleci/config.yml
            git diff --exit-code


workflows:
  my-workflow:
    jobs:
      - check-config-pack
