version: 2.1
orbs:
  # Slack通知をするためのorb
  # https://circleci.com/orbs/registry/orb/circleci/slack
  slack: circleci/slack@2.4.0

jobs:
  build:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "builds docker image"
  push:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "push docker image"
  deploy-staging:
    docker:
      - image: cibuilds/base
    steps:
      - deploy:
          command: echo "deploy staging"
  deploy-production:
    docker:
      - image: cibuilds/base
    steps:
      - deploy:
          command: echo "deploy production"


workflows:
  my-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: docker
      - push:
          requires:
            - build
      - deploy-staging:
          requires:
            - push
      - deploy-production:
          requires:
            - push
