version: 2.1
orbs:
  # Slack通知をするためのorb
  # https://circleci.com/orbs/registry/orb/circleci/slack
  slack: circleci/slack@2.4.0

jobs:
  start:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "Start the workflow"
  static-checks:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "exec static check"
  bundle-install:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "exec bundle install"
  yarn-install:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "exec yarn install"
  jest:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "exec jest"
  rspec:
    docker:
      - image: cibuilds/base
    steps:
      - run: echo "exec rspec"


workflows:
  my-workflow:
    jobs:
      - start:
          filters:
            branches:
              only: master
      - static-checks:
          requires:
            - start
      - yarn-install:
          requires:
            - start
      - bundle-install:
          requires:
            - start
      - jest:
          requires:
            - yarn-install
      - rspec:
          requires:
            - yarn-install
            - bundle-install
      # Deployの準備ができたことをSlackに通知する
      # approveしたときのみdeployされる
#      - slack/approval-notification:
#          message: Pending approval

